version: 0.2

phases:
    install:
        commands:
            - cp ./settings.xml /root/.m2/settings.xml
        runtime-versions:
            java: openjdk8
    build:
        commands:
            - echo Build started on `date`
            - ./mvnw verify
    post_build:
        commands:
            - echo Build completed on `date`
            - ./mvnw -Pprod clean verify
artifacts:
    files:
        - target/umsl-1.0-SNAPSHOT.jar
        - appspec.yaml
    discard-paths: yes
