version: 0.2

phases:
    install:
        runtime-versions:
            java: corretto8
    build:
        commands:
            - echo Build started on `date`
            - ./mvnw verify
    post_build:
        commands:
            - echo Build completed on `date`
            - ./mvnw package
artifacts:
    files:
        - target/umsl-1.0-SNAPSHOT.jar
        - appspec.yml
    discard-paths: yes
